In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv('house-prices/test.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [17]:
df = df[['MSZoning', 'LotFrontage', 'LotArea', 'BldgType', 'OverallQual', 'OverallCond', 'YearBuilt', 'Foundation', 'BsmtCond', 'TotalBsmtSF', '1stFlrSF' ,'2ndFlrSF' , 'GrLivArea' , 'KitchenQual' ,'TotRmsAbvGrd' , 'GarageType' , 'GarageCars' , 'GarageArea' , 'GarageQual' , 'GarageCond' , 'PoolArea' , 'PoolQC' , 'Fence' , 'MiscFeature', 'MiscVal' , 'SaleType' ,  'SaleCondition' ,'RoofStyle', 'RoofMatl' , 'Exterior1st', 'Exterior2nd' , 'ExterQual', 'ExterCond' , 'BsmtQual', 'CentralAir', 'YrSold']]

In [18]:
np.round(df.isnull().mean()*100,2)

MSZoning          0.27
LotFrontage      15.56
LotArea           0.00
BldgType          0.00
OverallQual       0.00
OverallCond       0.00
YearBuilt         0.00
Foundation        0.00
BsmtCond          3.08
TotalBsmtSF       0.07
1stFlrSF          0.00
2ndFlrSF          0.00
GrLivArea         0.00
KitchenQual       0.07
TotRmsAbvGrd      0.00
GarageType        5.21
GarageCars        0.07
GarageArea        0.07
GarageQual        5.35
GarageCond        5.35
PoolArea          0.00
PoolQC           99.79
Fence            80.12
MiscFeature      96.50
MiscVal           0.00
SaleType          0.07
SaleCondition     0.00
RoofStyle         0.00
RoofMatl          0.00
Exterior1st       0.07
Exterior2nd       0.07
ExterQual         0.00
ExterCond         0.00
BsmtQual          3.02
CentralAir        0.00
YrSold            0.00
dtype: float64

In [19]:
df.drop(columns=['PoolQC','Fence','MiscFeature'],inplace=True)

C:\Users\HP TECHNOLOGY\AppData\Local\Temp\ipykernel_6364\4177526432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['PoolQC','Fence','MiscFeature'],inplace=True)

In [20]:
df

,MSZoning,LotFrontage,LotArea,BldgType,OverallQual,OverallCond,YearBuilt,Foundation,BsmtCond,TotalBsmtSF,...,SaleCondition,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,BsmtQual,CentralAir,YrSold
0,RH,80.0,11622,1Fam,5,6,1961,CBlock,TA,882.0,...,Normal,Gable,CompShg,VinylSd,VinylSd,TA,TA,TA,Y,2010
1,RL,81.0,14267,1Fam,6,6,1958,CBlock,TA,1329.0,...,Normal,Hip,CompShg,Wd Sdng,Wd Sdng,TA,TA,TA,Y,2010
2,RL,74.0,13830,1Fam,5,5,1997,PConc,TA,928.0,...,Normal,Gable,CompShg,VinylSd,VinylSd,TA,TA,Gd,Y,2010
3,RL,78.0,9978,1Fam,6,6,1998,PConc,TA,926.0,...,Normal,Gable,CompShg,VinylSd,VinylSd,TA,TA,TA,Y,2010
4,RL,43.0,5005,TwnhsE,8,5,1992,PConc,TA,1280.0,...,Normal,Gable,CompShg,HdBoard,HdBoard,Gd,TA,Gd,Y,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,RM,21.0,1936,Twnhs,4,7,1970,CBlock,TA,546.0,...,Normal,Gable,CompShg,CemntBd,CmentBd,TA,TA,TA,Y,2006
1455,RM,21.0,1894,TwnhsE,4,5,1970,CBlock,TA,546.0,...,Abnorml,Gable,CompShg,CemntBd,CmentBd,TA,TA,TA,Y,2006
1456,RL,160.0,20000,1Fam,5,7,1960,CBlock,TA,1224.0,...,Abnorml,Gable,CompShg,VinylSd,VinylSd,TA,TA,TA,Y,2006
1457,RL,62.0,10441,1Fam,5,5,1992,PConc,TA,912.0,...,Normal,Gable,CompShg,HdBoard,Wd Shng,TA,TA,Gd,Y,2006
1458,RL,74.0,9627,1Fam,7,5,1993,PConc,TA,996.0,...,Normal,Gable,CompShg,HdBoard,HdBoard,TA,TA,Gd,Y,2006

In [21]:
np.round(df.isnull().mean()*100,2)

MSZoning          0.27
LotFrontage      15.56
LotArea           0.00
BldgType          0.00
OverallQual       0.00
OverallCond       0.00
YearBuilt         0.00
Foundation        0.00
BsmtCond          3.08
TotalBsmtSF       0.07
1stFlrSF          0.00
2ndFlrSF          0.00
GrLivArea         0.00
KitchenQual       0.07
TotRmsAbvGrd      0.00
GarageType        5.21
GarageCars        0.07
GarageArea        0.07
GarageQual        5.35
GarageCond        5.35
PoolArea          0.00
MiscVal           0.00
SaleType          0.07
SaleCondition     0.00
RoofStyle         0.00
RoofMatl          0.00
Exterior1st       0.07
Exterior2nd       0.07
ExterQual         0.00
ExterCond         0.00
BsmtQual          3.02
CentralAir        0.00
YrSold            0.00
dtype: float64

In [22]:
cat_encoded = ['OverallQual', 'OverallCond',]

categoricalColumns = ['MSZoning', 'BldgType',  'Foundation', 'BsmtCond',   'KitchenQual' , 'GarageType' ,  'GarageQual' , 'GarageCond' ,  'SaleType' ,  'SaleCondition' ,'RoofStyle', 'RoofMatl' , 'Exterior1st', 'Exterior2nd' , 'ExterQual', 'ExterCond' , 'BsmtQual', 'CentralAir']


numaricalColumns = ['LotFrontage', 'LotArea','YearBuilt','YrSold', 'TotalBsmtSF', '1stFlrSF' ,'2ndFlrSF' ,'GrLivArea' ,'TotRmsAbvGrd' , 'GarageCars' , 'GarageArea' ,'PoolArea' , 'MiscVal' ,'SalePrice']

In [23]:
df[categoricalColumns]

,MSZoning,BldgType,Foundation,BsmtCond,KitchenQual,GarageType,GarageQual,GarageCond,SaleType,SaleCondition,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,BsmtQual,CentralAir
0,RH,1Fam,CBlock,TA,TA,Attchd,TA,TA,WD,Normal,Gable,CompShg,VinylSd,VinylSd,TA,TA,TA,Y
1,RL,1Fam,CBlock,TA,Gd,Attchd,TA,TA,WD,Normal,Hip,CompShg,Wd Sdng,Wd Sdng,TA,TA,TA,Y
2,RL,1Fam,PConc,TA,TA,Attchd,TA,TA,WD,Normal,Gable,CompShg,VinylSd,VinylSd,TA,TA,Gd,Y
3,RL,1Fam,PConc,TA,Gd,Attchd,TA,TA,WD,Normal,Gable,CompShg,VinylSd,VinylSd,TA,TA,TA,Y
4,RL,TwnhsE,PConc,TA,Gd,Attchd,TA,TA,WD,Normal,Gable,CompShg,HdBoard,HdBoard,Gd,TA,Gd,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,RM,Twnhs,CBlock,TA,TA,NaN,NaN,NaN,WD,Normal,Gable,CompShg,CemntBd,CmentBd,TA,TA,TA,Y
1455,RM,TwnhsE,CBlock,TA,TA,CarPort,TA,TA,WD,Abnorml,Gable,CompShg,CemntBd,CmentBd,TA,TA,TA,Y
1456,RL,1Fam,CBlock,TA,TA,Detchd,TA,TA,WD,Abnorml,Gable,CompShg,VinylSd,VinylSd,TA,TA,TA,Y
1457,RL,1Fam,PConc,TA,TA,NaN,NaN,NaN,WD,Normal,Gable,CompShg,HdBoard,Wd Shng,TA,TA,Gd,Y
1458,RL,1Fam,PConc,TA,TA,Attchd,TA,TA,WD,Normal,Gable,CompShg,HdBoard,HdBoard,TA,TA,Gd,Y

In [24]:
categoricalColumns = ['MSZoning', 'BldgType',  'Foundation', 'BsmtCond',   'KitchenQual' , 'GarageType' ,  'GarageQual' , 'GarageCond' ,  'SaleType' ,  'SaleCondition' ,'RoofStyle', 'RoofMatl' , 'Exterior1st', 'Exterior2nd' , 'ExterQual', 'ExterCond' , 'BsmtQual', 'CentralAir']

cat_impute = ['BsmtCond','GarageType','GarageQual' , 'GarageCond' , 'BsmtQual']

ordinalColumns = ['BsmtCond', 'KitchenQual' ,'GarageQual' , 'GarageCond' ,'ExterQual', 'ExterCond' , 'BsmtQual']
oneHotColumns = ['MSZoning', 'BldgType',  'Foundation',    'GarageType' ,    'SaleType' ,  'SaleCondition' ,'RoofStyle', 'RoofMatl' , 'Exterior1st', 'Exterior2nd' ,  'CentralAir']

In [25]:
numaricalColumns = ['LotFrontage', 'OverallQual', 'OverallCond', 'LotArea','YearBuilt','YrSold', 'TotalBsmtSF', '1stFlrSF' ,'2ndFlrSF' ,'GrLivArea' ,'TotRmsAbvGrd' , 'GarageCars' , 'GarageArea' ,'PoolArea' , 'MiscVal' ,'SalePrice']

num_impute = ['LotFrontage']

In [26]:
np.round(df.isnull().mean()*100,2)

MSZoning          0.27
LotFrontage      15.56
LotArea           0.00
BldgType          0.00
OverallQual       0.00
OverallCond       0.00
YearBuilt         0.00
Foundation        0.00
BsmtCond          3.08
TotalBsmtSF       0.07
1stFlrSF          0.00
2ndFlrSF          0.00
GrLivArea         0.00
KitchenQual       0.07
TotRmsAbvGrd      0.00
GarageType        5.21
GarageCars        0.07
GarageArea        0.07
GarageQual        5.35
GarageCond        5.35
PoolArea          0.00
MiscVal           0.00
SaleType          0.07
SaleCondition     0.00
RoofStyle         0.00
RoofMatl          0.00
Exterior1st       0.07
Exterior2nd       0.07
ExterQual         0.00
ExterCond         0.00
BsmtQual          3.02
CentralAir        0.00
YrSold            0.00
dtype: float64

In [27]:
for col in categoricalColumns:
    print(df[col].value_counts())
    print("-----------------------------------")

MSZoning
RL         1114
RM          242
FV           74
C (all)      15
RH           10
Name: count, dtype: int64
-----------------------------------
BldgType
1Fam      1205
TwnhsE     113
Duplex      57
Twnhs       53
2fmCon      31
Name: count, dtype: int64
-----------------------------------
Foundation
PConc     661
CBlock    601
BrkTil    165
Slab       25
Stone       5
Wood        2
Name: count, dtype: int64
-----------------------------------
BsmtCond
TA    1295
Fa      59
Gd      57
Po       3
Name: count, dtype: int64
-----------------------------------
KitchenQual
TA    757
Gd    565
Ex    105
Fa     31
Name: count, dtype: int64
-----------------------------------
GarageType
Attchd     853
Detchd     392
BuiltIn     98
Basment     17
2Types      17
CarPort      6
Name: count, dtype: int64
-----------------------------------
GarageQual
TA    1293
Fa      76
Gd      10
Po       2
Name: count, dtype: int64
-----------------------------------
GarageCond
TA    1328
Fa      39
Po       7
Gd       6
Ex       1
Name: count, dtype: int64
-----------------------------------
SaleType
WD       1258
New       117
COD        44
ConLD      17
CWD         8
Oth         4
ConLI       4
Con         3
ConLw       3
Name: count, dtype: int64
-----------------------------------
SaleCondition
Normal     1204
Partial     120
Abnorml      89
Family       26
Alloca       12
AdjLand       8
Name: count, dtype: int64
-----------------------------------
RoofStyle
Gable      1169
Hip         265
Gambrel      11
Flat          7
Mansard       4
Shed          3
Name: count, dtype: int64
-----------------------------------
RoofMatl
CompShg    1442
Tar&Grv      12
WdShake       4
WdShngl       1
Name: count, dtype: int64
-----------------------------------
Exterior1st
VinylSd    510
MetalSd    230
HdBoard    220
Wd Sdng    205
Plywood    113
CemntBd     65
BrkFace     37
WdShing     30
AsbShng     24
Stucco      18
BrkComm      4
AsphShn      1
CBlock       1
Name: count, dtype: int64
-----------------------------------
Exterior2nd
VinylSd    510
MetalSd    233
HdBoard    199
Wd Sdng    194
Plywood    128
CmentBd     66
Wd Shng     43
BrkFace     22
Stucco      21
AsbShng     18
Brk Cmn     15
ImStucc      5
CBlock       2
AsphShn      1
Stone        1
Name: count, dtype: int64
-----------------------------------
ExterQual
TA    892
Gd    491
Ex     55
Fa     21
Name: count, dtype: int64
-----------------------------------
ExterCond
TA    1256
Gd     153
Fa      39
Ex       9
Po       2
Name: count, dtype: int64
-----------------------------------
BsmtQual
TA    634
Gd    591
Ex    137
Fa     53
Name: count, dtype: int64
-----------------------------------
CentralAir
Y    1358
N     101
Name: count, dtype: int64
-----------------------------------

In [28]:
for col in categoricalColumns:
    print(df[col].nunique(),col)

5 MSZoning
5 BldgType
6 Foundation
4 BsmtCond
4 KitchenQual
6 GarageType
4 GarageQual
5 GarageCond
9 SaleType
6 SaleCondition
6 RoofStyle
4 RoofMatl
13 Exterior1st
15 Exterior2nd
4 ExterQual
5 ExterCond
4 BsmtQual
2 CentralAir

In [29]:
df[numaricalColumns]

KeyError: "['SalePrice'] not in index"

In [ ]:
df['YearBuilt'] = pd.to_datetime(df['YearBuilt']).dt.year
df['YrSold'] = pd.to_datetime(df['YrSold']).dt.year

In [ ]:
df.info()